# This file was generated by GoReleaser. DO NOT EDIT.
cask "bort" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "f2bce26a89180c0f836d94af04d6305a7c7144b15ebe013f7e896081554e367c"
      url "https://github.com/aikins01/bort/releases/download/v#{version}/bort_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3c14a5d23a9706406e3a165bb69eb69ceaca87c23e5bd8b697e1e5e6089c1484"
      url "https://github.com/aikins01/bort/releases/download/v#{version}/bort_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e0083b1bbee65323901926a26bde9a2bef1b46b6935bc0d98cec8bb534e01579"
      url "https://github.com/aikins01/bort/releases/download/v#{version}/bort_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "0aead85e1e740aa57a933fc6c252dd0a13d8b9dad40fbcfc73f7d046f307fb6d"
      url "https://github.com/aikins01/bort/releases/download/v#{version}/bort_Linux_arm64.tar.gz"
    end
  end

  name "bort"
  desc "migration cockpit for self-hosted PaaS platform moves"
  homepage "https://github.com/aikins01/bort"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bort"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bort"]
    end
  end

  # No zap stanza required

end
