# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bort < Formula
  desc "migration cockpit for self-hosted PaaS platform moves"
  homepage "https://github.com/aikins01/bort"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/aikins01/bort/releases/download/v0.1.0/bort_Darwin_x86_64.tar.gz"
      sha256 "9eb90f6bed3ecc716b15da6e9ef6415bfada1b7be09af6595e2b8e7fcd973ff8"

      define_method(:install) do
        bin.install "bort"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/aikins01/bort/releases/download/v0.1.0/bort_Darwin_arm64.tar.gz"
      sha256 "ba563c1243ce0994089376ee26e36f6e3224156d14cede37783f5ec630281711"

      define_method(:install) do
        bin.install "bort"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/aikins01/bort/releases/download/v0.1.0/bort_Linux_x86_64.tar.gz"
      sha256 "3d7602c3659a10498656739253ca149828312dfd9ad563c0b3107ce0290745ed"
      define_method(:install) do
        bin.install "bort"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/aikins01/bort/releases/download/v0.1.0/bort_Linux_arm64.tar.gz"
      sha256 "b1cd424575580cf8d257626f5e2eece62c3e7485b93f9db67237c96abbec9ed7"
      define_method(:install) do
        bin.install "bort"
      end
    end
  end

  test do
    system "#{bin}/bort", "version"
  end
end
